### ISSUE TITLE
a lot of errors

### ISSUE THREAD

**Issue by sirrajahmed** [hydrogen11/store_ex#1]
hey man, i was following the tutorial but getting a lot of errors therefore i thought to pull down your project.

Once I pulled down the project there are a lot of errors and it wont even let me launch the website.

Could you give a few more details on how to set up the website after pulling it down.

**Comment by davidtrushkov** [comment]
Ok, what are the errors your getting?

**Comment by davidtrushkov** [comment]
Yes, sure. What errors are you getting?

**Comment by nicolasdanelon** [comment]
ahahahaha please close this issue! is point less and refered to https://github.com/davidtrushkov/store/
